### ISSUE TITLE
Vendetta doesn't load

### ISSUE THREAD

**Issue by XanderTheDev** [vendetta-mod/VendettaManager#102]
When I install the vendetta app via the vendetta manager I get this error:
![Screenshot_20240426-220501_Vendetta](https://github.com/vendetta-mod/VendettaManager/assets/101188151/493d92e8-5acc-4870-a2bf-304f32d8fa14)

I don't know if this is on my end or because of the app. The only thing I can think why it's on my end is because I had VendettaXposed before this (which I had deleted before hand of this). Can someone tell me what I need to do to fix this? And otherwise this is just a issue of the app.

**Comment by yszwa** [comment]
i have same issue.

**Comment by twinflac** [comment]
this is a problem with "new" vendetta-xposed release maybe in "material you" theme that no compatible with android =>14(sdk34) [flgit.flcord](https://git.flctwn.org/flactwin/flcord/releases)
my stable builds are compiled with older version and fully compatible with android 6-15

**Comment by Cynosphere** [comment]
Please don't use closed issues to advertise your malware.

**Comment by twinflac** [comment]
why you point this malware?
im just try to help(

**Comment by twinflac** [comment]
if you not trust you can check this apks and after this i will belive you

**Comment by twinflac** [comment]
![ResizedImage_2024-07-07_00-48-30_3884](https://github.com/vendetta-mod/VendettaManager/assets/87523240/27c802d8-ff58-46f8-a3b3-5d5a8b3210b5)
this version conflict with android 14, when i updated from lineageos 20 to 21 i get this issue, older xposed versions work fine

**Comment by twinflac** [comment]
my little solution for guys who wish to bould it by self:
1. install vendetta-manager and try to install and patch disxord using in-app interface
2. after it not install patched discord on your phone but download another any version of discord from apkmirror or apkpure site in .xapk format or just replace vendetta.apk file with old version skip to step 7
3. unarchive it anywhere, this is just zip archive
4. you need com.dicord.apk config.en.apk config.xxhdpi.apk files
5. copy this all to directory Android/data/dev.beefers.vendetta.manager/cache/236020/
6. and rename com.discord.apk to base-236020.apk, config.arm64_v8a.apk to config.arm64_v8a-236020.apk, config.en.apk to config.en-236020.apk and config.xxhdpi.apk to config.xxhdpi-236020.apk
7. download https://github.com/vendetta-mod/VendettaXposed/releases/download/7/app-release.apk and rename it as vendetta.apk and replace another in Android/data/dev.beefers.vendetta.manager/cache/
8. after all try to install patched vendetta again
9. i hope i've helped you
![Screenshot_20240707-011235_Trebuchet](https://github.com/vendetta-mod/VendettaManager/assets/87523240/e8fad18e-a821-4b96-9423-c52de5cec30d)

![Screenshot_20240707-011214_ZArchiver](https://github.com/vendetta-mod/VendettaManager/assets/87523240/fb300bb3-e87f-4903-8756-488eef608dd2)

![Screenshot_20240707-012248_Trebuchet](https://github.com/vendetta-mod/VendettaManager/assets/87523240/d2541c59-c174-41f1-b546-2ed32d2d7694)

**Comment by twinflac** [comment]
p.s. instead of blaming everyone else for spreading the malware, please sort out the compatibility of your software, thx

**Comment by Cynosphere** [comment]
> p.s. instead of blaming everyone else for spreading the malware, please sort out the compatibility of your software, thx

![reading comprehension 0](https://toaster.sh/i/egyy2lyv.png)

**Comment by twinflac** [comment]
grim

**Comment by ghost** [comment]
> > p.s. instead of blaming everyone else for spreading the malware, please sort out the compatibility of your software, thx
> 
> ![reading comprehension 0](https://toaster.sh/i/egyy2lyv.png)

I think you should add a disclaimer regarding the Vendetta being EOL to this repo's readme too.

**Comment by twinflac** [comment]
i will think about it

**Comment by yszwa** [comment]
use random forks

**Comment by twinflac** [comment]
maybe one day we will make our good custom mobile/desktop clients)

**Comment by twinflac** [comment]
using material you and gtk theme engines
