### ISSUE TITLE
[Feature Request] In-built Applock 

### ISSUE THREAD

**Issue by Mathew20kdroid** [vendetta-mod/VendettaManager#105]
Please add an option to **Lock** the app ( not the Manager but the **Bunny Discord** app)

**Comment by Cynosphere** [comment]
just use an already existing locker app

**Comment by Mathew20kdroid** [comment]
Most phones don't have an in-built Applock, and the 3rd party ones suck...

**Comment by Cynosphere** [comment]
womp womp

this isn't the right repo

**Comment by Mathew20kdroid** [comment]
😅 can you link me the right one...

**Comment by Cynosphere** [comment]
![screenshot of the search bar](https://toaster.sh/i/rgn7pzre.png)

**Comment by Mathew20kdroid** [comment]
Sorry my bad 😅😅😆
