### ISSUE TITLE
Update notifications are noisy

### ISSUE THREAD

**Issue by rollingmoai** [vendetta-mod/VendettaManager#17]
These update notifications are annoying, especially when it's just a duplicate:

![image](https://github.com/vendetta-mod/VendettaManager/assets/75471378/8a3ba20b-2d2f-4cd3-a2fe-b86a67d69850)

There should be just one persistent notification for this.

**Comment by wingio** [comment]
either increase the updater duration or disable it

**Comment by wingio** [comment]
i can add a button to the notification to ignore that specific update, or maybe setting the notifications id to the version might work

**Comment by riichimaru** [comment]
> There should be just one persistent notification for this.

i think the main point is "update when you want", so just giving persistent notification, which in fact is more annoying, strange
either set more checking duration, because only if u use alpha u will need **daily**, not even close, or use xposed module to update with google play
