### ISSUE TITLE
Amoled

### ISSUE THREAD

**Issue by sneazy-ibo** [vendetta-mod/VendettaManager#22]
please add the option to enable amoled over dark themes :)

**Comment by Cynosphere** [comment]
this is an option within discord itself if you tap dark mode 10 times, its just that recent discord versions have messed up the colors

do note that if some themes modify raw colors, it cannot be guaranteed that the color is exactly `#000000` still

(also this isnt the right place for requests)

**Comment by wingio** [comment]
if you're asking for amoled in manager itself im gonna have to decline, not really a point in creating a special theme for an app you're only on for a few minutes at a time
