### ISSUE TITLE
VendettaManager stops installing at the last task (Installing APK)

### ISSUE THREAD

**Issue by SoundCrafterYT** [vendetta-mod/VendettaManager#24]
First time installing this.

Vendetta Manager v1.0.86
Built from commit 20757ce on main (Changes Present)

Running Android 13, API level 33
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-190017.apk is cached
base-190017.apk is not cached, downloading now
Move base-190017.apk to working directory
Checking if config.arm64_v8a-190017.apk is cached
config.arm64_v8a-190017.apk is not cached, downloading now
Move config.arm64_v8a-190017.apk to working directory
Checking if config.en-190017.apk is cached
config.en-190017.apk is not cached, downloading now
Move config.en-190017.apk to working directory
Checking if config.xxhdpi-190017.apk is cached
config.xxhdpi-190017.apk is not cached, downloading now
Move config.xxhdpi-190017.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is not cached, downloading now
Move vendetta.apk to working directory
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Reading AndroidManifest.xml from base-190017.apk
Changing package and app name in base-190017.apk
Deleting old AndroidManifest.xml in base-190017.apk
Adding patched AndroidManifest.xml in base-190017.apk
Reading AndroidManifest.xml from config.arm64_v8a-190017.apk
Changing package and app name in config.arm64_v8a-190017.apk
Changing package name in config.arm64_v8a-190017.apk
Deleting old AndroidManifest.xml in config.arm64_v8a-190017.apk
Adding patched AndroidManifest.xml in config.arm64_v8a-190017.apk
Reading AndroidManifest.xml from config.en-190017.apk
Changing package and app name in config.en-190017.apk
Changing package name in config.en-190017.apk
Deleting old AndroidManifest.xml in config.en-190017.apk
Adding patched AndroidManifest.xml in config.en-190017.apk
Reading AndroidManifest.xml from config.xxhdpi-190017.apk
Changing package and app name in config.xxhdpi-190017.apk
Changing package name in config.xxhdpi-190017.apk
Deleting old AndroidManifest.xml in config.xxhdpi-190017.apk
Adding patched AndroidManifest.xml in config.xxhdpi-190017.apk
Creating dir for signed apks
Byte aligning base-190017.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.arm64_v8a-190017.apk
Byte aligning config.en-190017.apk
Removing old resources.arsc
Adding aligned resources.arsc
Byte aligning config.xxhdpi-190017.apk
Removing old resources.arsc
Adding aligned resources.arsc
Signing base-190017.apk
Signing config.arm64_v8a-190017.apk
Signing config.en-190017.apk
Signing config.xxhdpi-190017.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/base-190017.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/base-190017-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/base-190017.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: androidx.core.app.CoreComponentFactory
original minSdkVersion: 23
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/base-190017-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.arm64_v8a-190017.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.arm64_v8a-190017-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.arm64_v8a-190017.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.arm64_v8a-190017-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.en-190017.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.en-190017-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.en-190017.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.en-190017-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.xxhdpi-190017.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.xxhdpi-190017-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/signed/config.xxhdpi-190017.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/190017/patched/lspatched/config.xxhdpi-190017-375-lspatched.apk
Gathering final apks
Installing apks

Failed on step INSTALL_APK

java.io.IOException: Failed to allocate 42719396 because only 30654464 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
	at android.os.Parcel.readParcelable(Parcel.java:4755)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:565)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:1110)
	at dev.beefers.vendetta.manager.installer.util.PackageInstallerKt.installApks(PackageInstaller.kt:29)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.install(InstallerViewModel.kt:379)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel.access$install(InstallerViewModel.kt:40)
	at dev.beefers.vendetta.manager.ui.viewmodel.installer.InstallerViewModel$install$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerSession.openWrite(PackageInstallerSession.java:1513)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:286)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)

**Comment by riichi34** [comment]
not enough space

**Comment by Gabe616** [comment]
nya

**Comment by riichi34** [comment]
as long says,
> Failed to allocate 42719396 because only 30654464 allocatable

**Comment by aeongdesu** [comment]
please use codeblock or post to pastebin in next time...

\```
some logs here
\```
