### ISSUE TITLE
Suggestion: Export to APK

### ISSUE THREAD

**Issue by AymenAbb** [vendetta-mod/VendettaManager#25]
Similar to ReVanced Manager, once compiling is finished I'd love a feature where I can export to APK. Yes I know this can cause havoc between kids sharing files that may not be safe, but I literally have no way to test previous versions.

**Comment by wingio** [comment]
if you tap the version in the about screen 10 times you can access dev settings, there you can change the discord version

**Comment by AymenAbb** [comment]
Thank you.
