### ISSUE TITLE
(More) Advanced Settings

### ISSUE THREAD

**Issue by nightznero** [vendetta-mod/VendettaManager#26]
Hello @wingio ,
I would ask it is possible to add more (advanced) settings in `advanced` or `developer` sections.
Like;
• option to choose languages rather than downloading all modules
• choose specific arch
And the most important for me:
•option to disable `app.adjust.xyz` analysis. Ik that auto reports are needed for further solving problems but users can do it manually and `Adjust` spam pings to their 3domains.

Best Regards, NIGHTZNERO.

**Comment by nightznero** [comment]
> Manager only downloads one locale, discord themselves don't actually use it but its still required.
> 
Understandable 

> Manager selects the architecture based on what's supported by your device
> 
Ye but if device supports v8 as well as v7,does it download only v8?

> Manager doesn't use analytics software at all
>
Manager maybe yes but I mean to implement it INTO manager(to clarify)
I dont use official version of DC but Vendetta DC pings all the time `app adjust` and if it's only used by Vendetta would be nice to disable it

**Comment by wingio** [comment]
> Ye but if device supports v8 as well as v7,does it download only v8?
Im fairly certain it picks whatever your device lists first

> Manager maybe yes but I mean to implement it INTO manager(to clarify)
> I dont use official version of DC but Vendetta DC pings all the time app adjust and if it's only used by Vendetta would be nice to disable it
This could be added to the NoTrack plugin if it isn't already (@maisymoe ?)

**Comment by xDARKxDEVILx** [comment]
How about the option to choose custom icon instead of discord or vendetta icons, you choose your own

**Comment by nightznero** [comment]
> How about the option to choose custom icon instead of discord or vendetta icons, you choose your own

#7 was already question bout dat and not for a first time. Its declined idea

**Comment by xDARKxDEVILx** [comment]
> > How about the option to choose custom icon instead of discord or vendetta icons, you choose your own
> 
> #7 was already question bout dat and not for a first time. Its declined idea

Yeah, i looked at it, it is unfortunate that it was declined, I wanted to set the icon to something funny, and i am not sure if i like the alternative ways of doing so

**Comment by nightznero** [comment]
Well,so any news bout that? Cuz issue has been closed,NoTrack plugin is installed but DCV still pings _adjust_ @wingio ?
![Screenshot_20230912_123449.png](https://github.com/vendetta-mod/VendettaManager/assets/61750641/98ec1c8d-b21f-4560-99e0-d4dd4fccced4)
![Screenshot_20230912_123647_AdGuard.png](https://github.com/vendetta-mod/VendettaManager/assets/61750641/1f24947d-0c52-419d-a925-c72191dd6dbd)

**Comment by wingio** [comment]
Its not something manager can block, request it in NoTracks repo
