### ISSUE TITLE
Bug(failed to install: unknown reason)

### ISSUE THREAD

**Issue by xDARKxDEVILx** [vendetta-mod/VendettaManager#28]
I get the toast message in the title when trying to install vendetta after it finishes, everything seemed correct, i tried 3 times with no luck 

Here is a screenshot 
![IMG_20230818_171827](https://github.com/vendetta-mod/VendettaManager/assets/120474122/1b34f35a-12b4-4b6e-82af-0316c51da09d)

Here are the logs when i click copy logs
Vendetta Manager v1.0.87
Built from commit cee4d01 on main (Changes Present)

Running Android 11, API level 30
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi

Checking if base-191016.apk is cached
base-191016.apk is cached
Move base-191016.apk to working directory
Checking if config.arm64_v8a-191016.apk is cached
config.arm64_v8a-191016.apk is cached
Move config.arm64_v8a-191016.apk to working directory
Checking if config.en-191016.apk is cached
config.en-191016.apk is cached
Move config.en-191016.apk to working directory
Checking if config.xxhdpi-191016.apk is cached
config.xxhdpi-191016.apk is cached
Move config.xxhdpi-191016.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is cached
Move vendetta.apk to working directory
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Reading AndroidManifest.xml from base-191016.apk
Changing package and app name in base-191016.apk
Deleting old AndroidManifest.xml in base-191016.apk
Adding patched AndroidManifest.xml in base-191016.apk
Reading AndroidManifest.xml from config.arm64_v8a-191016.apk
Changing package and app name in config.arm64_v8a-191016.apk
Changing package name in config.arm64_v8a-191016.apk
Deleting old AndroidManifest.xml in config.arm64_v8a-191016.apk
Adding patched AndroidManifest.xml in config.arm64_v8a-191016.apk
Reading AndroidManifest.xml from config.en-191016.apk
Changing package and app name in config.en-191016.apk
Changing package name in config.en-191016.apk
Deleting old AndroidManifest.xml in config.en-191016.apk
Adding patched AndroidManifest.xml in config.en-191016.apk
Reading AndroidManifest.xml from config.xxhdpi-191016.apk
Changing package and app name in config.xxhdpi-191016.apk
Changing package name in config.xxhdpi-191016.apk
Deleting old AndroidManifest.xml in config.xxhdpi-191016.apk
Adding patched AndroidManifest.xml in config.xxhdpi-191016.apk
Creating dir for signed apks
Signing base-191016.apk
Signing config.arm64_v8a-191016.apk
Signing config.en-191016.apk
Signing config.xxhdpi-191016.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/base-191016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/base-191016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/base-191016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: androidx.core.app.CoreComponentFactory
original minSdkVersion: 23
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/base-191016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.arm64_v8a-191016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.arm64_v8a-191016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.arm64_v8a-191016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.arm64_v8a-191016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.en-191016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.en-191016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.en-191016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.en-191016-375-lspatched.apk
Processing /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.xxhdpi-191016.apk -> /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.xxhdpi-191016-375-lspatched.apk
apk path: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/signed/config.xxhdpi-191016.apk
Parsing original apk...
Register apk signer with custom keystore...
original appComponentFactory class: null
original minSdkVersion: 0
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.vendetta.xposed
Creating nested apk link...
Writing apk...
Done. Output APK: /storage/emulated/0/Android/data/dev.beefers.vendetta.manager/cache/191016/patched/lspatched/config.xxhdpi-191016-375-lspatched.apk
Gathering final apks
Installing apks

Everything looks correct from my understanding

**Comment by wingio** [comment]
what toast message

**Comment by xDARKxDEVILx** [comment]
> what toast message

The one in the title, i will send screenrecording of the installation

**Comment by xDARKxDEVILx** [comment]
https://github.com/vendetta-mod/VendettaManager/assets/120474122/9818e9f8-bf25-41a4-8732-4edecae7b929

**Comment by wingio** [comment]
try to install the apks manually using SAI

**Comment by xDARKxDEVILx** [comment]
> try to install the apks manually using SAI

You mean each apk that was downloaded separately?
Or the final vendetta apk?

**Comment by wingio** [comment]
select all of the apks in /sdcard/Android/data/dev.beefers.vendetta.manager/cache/{version}/patched/lspatched

**Comment by xDARKxDEVILx** [comment]
Alright got it, will try that and report back

**Comment by xDARKxDEVILx** [comment]
> select all of the apks in /sdcard/Android/data/dev.beefers.vendetta.manager/cache/{version}/patched/lspatched

Just nevermind, it was fucking MIUI optimization setting being on, turned it off and it worked, you can close this now
