### ISSUE TITLE
feat: Add timestamp to commits in changelog

### ISSUE THREAD

**Issue by KobeW50** [vendetta-mod/VendettaManager#36]
Perhaps the main purpose of the commits is to show new features, which will encourage users to update to newer versions. But without timestamps it is difficult for the user to know which commits are new and which they already have.

Example of how it would look:

![photostudio_1698201551837.jpg](https://github.com/vendetta-mod/VendettaManager/assets/84587632/89f02b99-95ac-47c0-a059-9938301c6efa)

**Comment by wingio** [comment]
Oh manager doesn't update Vendetta itself (that's done in app) - it just updates the base discord version manager injects in

I could still add this though, just as a bit of additional information
