### ISSUE TITLE
Potential Spyware in Vendetta Manager

### ISSUE THREAD

**Issue by kekmacska** [vendetta-mod/VendettaManager#39]
I have detected Trojan.Android.RemoteControl in Vendetta Manager's apk with Virustotal API: https://www.virustotal.com/gui/file/52552ee331bdc2ef32d5932990b12fa256ce005c4f133892dcc23cbadb946afd/detection

If you think it might be a false positive, i have detected a known spyware, slf4j Timber in the app, using Warden spyware and logger detector.
Does anyone know about this?

**Comment by maisymoe** [comment]
The first one is quite obviously a false positive - only one AV engine detected it, and one that I have never even heard of...

As for the second, what are you talking about? `slf4j-timber` is a binding between logging libraries for on-device debug logs, not a spyware.

Please do not rely on crappy antimalware solutions and instead educate yourself before opening issues like this.
