### ISSUE TITLE
[Enhancement/Feature] Option in settings to change the package name

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [vendetta-mod/VendettaManager#4]
I would like an option to be able to change the package name, not of the Vendetta manager but of the patched discord. 

This option would make the lives of people who use 3rd party launchers and icon packs and/or people who have a Samsung device and use GoodLock along with theme park to apply an icon pack system wide so much easier as people can change the package name to be the same package name that the official discord app has.

In case you aren't aware, icon packs apply icons based on the app's package name. For example, if the icon pack has an icon for the package name "com.discord", the icon pack will look and see if an application with the package name "com.discord" is installed, and if it is, it will apply the icon it has for the application with the package name "com.discord".

**Comment by aeongdesu** [comment]
it exists if you turn on the dev settings, tap the version in the about page 10 times
