### ISSUE TITLE
Some strings say "apk" instead of "APK"

### ISSUE THREAD

**Issue by KobeW50** [vendetta-mod/VendettaManager#41]
Some strings on the patching screen in the 'Download APKs' section say "apk" instead of "APK". The capitalized form is used in some steps on the screen so they should be consistent and the capitalized form is how it is officially written.

![SmartSelect_20231114_223502_Vendetta Manager.jpg](https://github.com/vendetta-mod/VendettaManager/assets/84587632/64011a48-3de8-45ae-b0d7-2e842fb62cf2)

![SmartSelect_20231114_223514_Vendetta Manager.jpg](https://github.com/vendetta-mod/VendettaManager/assets/84587632/0fc94488-31ec-4bfa-9dfc-1357aad029a9)

https://github.com/vendetta-mod/VendettaManager/blob/main/app/src/main/res/values/strings.xml#L21-L25

(Sorry I'm too lazy to PR)

**Comment by 1Lucas1apk** [comment]
Have you updated the app?

**Comment by KobeW50** [comment]
> Have you updated the app?

The manager is version 1.0.97

**Comment by 1Lucas1apk** [comment]
> > Have you updated the app?
> 
> The manager is version 1.0.97

Sorry, I didn't read the message directly, after I realized 😞, when I looked at the screenshot I thought it was another problem

**Comment by wingio** [comment]
all the strings are done on crowdin (link in the readme and app about page) it can be fixed there

**Comment by 1Lucas1apk** [comment]
You can change this at: https://crowdin.com/project/vendetta-manager

**Comment by KobeW50** [comment]
Thanks guys, I didn't realize the English strings were done on crowdin. *(I hope I did it correctly. This is my first time using crowdin)*
