### ISSUE TITLE
Add an option to choose a specific version of Discord

### ISSUE THREAD

**Issue by halotroop2288** [vendetta-mod/VendettaManager#45]
Now, with more controversial updates to the app coming out, I would like to be able to chose the specific version of the Discord app to base my Vendetta installation on (in particular, `205.15`).

I recommend using the route that ReVanced Manager uses:
Using the already-installed version of the app, or allowing the user to choose an APK file for patching, which they can acquire for themselves.
This simply bypasses the step of downloading the latest version from the app repository.

**Comment by nikosszzz** [comment]
Isn't this already a thing if you enable developer settings in the Manager?

**Comment by riivx** [comment]
> There isn't a "Developer Settings" section or option in the settings. And it's definitely not in the general settings, that I can see.

there is. go to info section (i icon) and press on version several times

**Comment by riivx** [comment]
> I recommend using the route that ReVanced Manager uses: Using the already-installed version of the app
requires root, i think. and if yes, then there is VendettaXposed, but anyways,

> or allowing the user to choose an APK file for patching
prepatched apks exist, just install them with SAI

**Comment by riivx** [comment]
> For one, that's really stupidly opaque.

have you ever accessed android developer settings? it's literally the same

> For two, that just crashes the app.

😨

**Comment by halotroop2288** [comment]
> > For one, that's really stupidly opaque.
>
> have you ever accessed android developer settings? it's literally the same

Yeah, and that's really stupidly opaque too. I blame Google. It wasn't always like that. Regardless, you don't have to copy bad UX.

> > I recommend using the route that ReVanced Manager uses: Using the already-installed version of the app
>
> requires root, i think. and if yes, then there is VendettaXposed, but anyways,

No. It does not. ReVanced only requires root if you would like to spoof YouTube (or other supported apps) as the original app, replacing the built-in version.

In fact if you were willing to change the way you make patches, even Vendetta could be installed with ReVanced Manager, as a ReVanced patch (hypothetically).

> > or allowing the user to choose an APK file for patching
> 
> prepatched apks exist, just install them with SAI

Donde esta?

**Comment by halotroop2288** [comment]
> base + language + arch config + dpi config

How would I parse that out of a consecutive build number like `209205`?
If you're talking about the file names (not the build number, which is how all of these are sorted) the base version isn't even included.

> base-360-lspatched.apk
> split_config.arm64_v8a-360-lspatched.apk
> split_config.armeabi_v7a-360-lspatched.apk
> split_config.de-360-lspatched.apk
> split_config.en-360-lspatched.apk
> split_config.hdpi-360-lspatched.apk
> split_config.x86_64-360-lspatched.apk
> split_config.xxhdpi-360-lspatched.apk

All I need to know is which one corresponds to which Discord app version.

And it really does not seem at this point like this is a viable alternative to just letting people choose the base APK to be patched by Vendetta Manager, without making them put in a cheat code that can crash the app in order to get to it.

**Comment by halotroop2288** [comment]
Yeah, I eventually figured out how your version system works. The equivalent of `205.15` is `205015` as if you're assuming the minor version will never exceed 999.
I installed the base and the split APKs for my architecture via `adb install-multiple` and it launches, but every icon is just missing.

> PS C:\Users\Administrator> adb install-multiple .\Downloads\base-360-lspatched.apk .\Downloads\split_config.arm64_v8a-360-lspatched.apk
> Success

So even though I'm one of the few that are technically skilled enough to figure that out, that workaround doesn't even work for me.

If this feature is already a part of the installer, please move it to a more accessible place! This could be a selling point of using Vendetta over other mods in a time where Discord seems hell-bent on making the experience worse.

**Comment by riivx** [comment]
for the love of god just use manager, that's the reason why it exists
if you have any problems with downloading try changing updates mirror and/or using vpn.
the whole point of manual installation is to help when other methods aren't working, and i bet they do work for you. if you want to get specific version - open developer settings in manager and just enter the version you need. version number is in #android-updates in discord.

**Comment by janisslsm** [comment]
> The equivalent of `205.15` is `205015` as if you're assuming the minor version will never exceed 999.

That's Discord's versioning scheme since forever (you can fetch it with those version codes from gplay) so vendetta just reuses them
