### ISSUE TITLE
Cannot load recent commits

### ISSUE THREAD

**Issue by tadghh** [vendetta-mod/VendettaManager#49]
Running vendetta manager 208.17 and the recent commits dont load on the home page, thought this could be marked as a "good first issue" running android 13

![Screenshot_20231217_211856_Vendetta Manager](https://github.com/vendetta-mod/VendettaManager/assets/47073445/be808fbe-5e87-43ce-81e4-0e180262ede1)

**Comment by AliucordKnifer** [comment]
Its probably a ratelimit, just wait and try again later

**Comment by tadghh** [comment]
> Its probably a ratelimit, just wait and try again later

Whoever takes this over could add
"Request to load commits timed out" along with downloading the commits for only the specific version. Honestly not sure about the rate limit suggestion unless somehow everyone is on the vendetta manager refreshing it

**Comment by wingio** [comment]
i was unaware it was happening to multiple users when i made that last comment

i tried the request in a browser and it worked fine, and my models still line up with the response. I'll have to do some actual debugging tomorrow
