### ISSUE TITLE
Enable R8

### ISSUE THREAD

**Issue by Iamlooker** [vendetta-mod/VendettaManager#51]
You can enable R8 to reduce apk size and also improve the app performance.

[Reference](https://developer.android.com/jetpack/compose/performance#build-release)

**Comment by wingio** [comment]
I've tried, but bc i use lspatch as a library it doesn't work

**Comment by Iamlooker** [comment]
Btw did you try configuring proguard? I havent worked with lspatch but I believe it can be fixed with the proguard configuration if not than its sad.

**Comment by wingio** [comment]
i couldn't find any useful resources about the specific issue
