### ISSUE TITLE
Vendetta Manager doesn't install from apk

### ISSUE THREAD

**Issue by DEFCON001** [vendetta-mod/VendettaManager#54]
Vendetta Manager doesn't install correctly, when prompted to to "install" and click "install" the app is not installed anywhere on the device. I have tried installing it from both work and default profiles, I have tired installing from different browsers, I have tried installing older versions too, and have the same issue. Any times I try to install from the APK again after the first attempt will lead to "Package installer keeps stopping". Rebooting the phone and trying again has not fixed the problem either.
Device:
Pixel 7 Pro
Calyx OS 5.2.0
Android 14

**Comment by riivx** [comment]
might be multiple profiles or installer issue, but still, can you show any logs from manager?

**Comment by DEFCON001** [comment]
I am unable to install the manager app, and hence unable to see any logs inside the app.

**Comment by riivx** [comment]
then that's definitely not a manager issue, might be calyxos related, corrupted file or something else

**Comment by nikander100** [comment]
This might actually be a device or apk issue.
I have the same problem.

Device:
Pixel 7
Stock ROM
Android 14

**Comment by DEFCON001** [comment]
> This might actually be a device or apk issue. I have the same problem.
> 
> Device: Pixel 7 Stock ROM Android 14

Okay this makes me feel a lot better about this as I couldn't find anyone else with this behavior and mostly gave up till now. I could try set up adb and see if I can get some logs from somewhere maybe, tho I've never touched adb before.

**Comment by DEFCON001** [comment]
Ohhh, I haven't tried adb, but stumbled across this: https://www.reddit.com/r/GooglePixel/comments/y2gsb0/pixel_7_cant_install_apks_from_external_sources/

Specifically comments like:
> Hi OP and [u/joblessdave123](https://www.reddit.com/user/joblessdave123/), I think the problem you're having is that the apps you're trying to sideload are 32-bit apps. [Google seems to have disabled support for 32-bit apps on the Pixel 7.](https://twitter.com/MishaalRahman/status/1580580220913954817)

Does anyone know if this app is made for 32 bit devices?
If so, can it be easily ported to a 64 bit version via a compile flag or something and have two releases?

**Comment by DEFCON001** [comment]
I just checked the apk in ark, seems it does have a arm-64v8a folder in the lib folder so I assume it is 64 bit...
Which leaves me at a dead end till I use adb,

**Comment by wingio** [comment]
try installing it with SAI, they usually give more detailed errors when installing apps

**Comment by Cynosphere** [comment]
Sounds like the same issue as https://github.com/libre-tube/LibreTube/issues/5406 if its truly an issue with universal APKs and whatever Google has done to Package Installer recently.

**Comment by neeeerrd** [comment]
Same thing happens to me

Pixel 6a
Stock Android
Android 14

**Comment by DEFCON001** [comment]
I have LibreTube installed fine tho... but it is from F-Droid. I tried uninstalling and re-installing and its fine, but maybe they are related somehow?...

**Comment by riivx** [comment]
cyn is probably right, google does lots of weird stuff with installer especially on pixels
try installing with adb, if it works - wontfix moment, call google

**Comment by GayPotatoEmma** [comment]
This is probably related to this [issue](https://issuetracker.google.com/issues/303849830) on the Pixels, which has since been fixed in the QPR2 Beta. I was having this issue too until that beta update on my Pixel 8 Pro

**Comment by haskayneharry** [comment]
Another Pixel 7 user here, and I have the same issue when I try to install the Vendetta Manager through my browser or third party file manager.
But opening the application file from Google's default Files app seems to successfully install the Vendetta Manager

System Details:
Pixel 7
Stock ROM
Android 14 (latest)

**Comment by wingio** [comment]
evidently this seems to be a problem with pixels and not manager itself, as such im gonna close this issue
