### ISSUE TITLE
The denial of Shizuku permission sometimes leads to spam requests

### ISSUE THREAD

**Issue by v1s7** [vendetta-mod/VendettaManager#58]
Screen recorded showcase: https://github.com/vendetta-mod/VendettaManager/assets/86906143/51a557d2-a0c9-4d98-bf71-829bfb3e4859

Device: RMX3085
Android: 13
Shizuku: 13.5.3.r1036.fff3f87
Vendetta Manager: 1.1.0

I don't think it's a bug on Shizuku's side. I tested it with other apps with Shizuku permissions under the same conditions and there was no spamming. I know you've been diligently working on this integration for a single feature, but I just don't want unnecessary permissions.

Lastly, I want to thank the team behind Vendetta for keeping all those quality projects active and alive. And the plugins/themes community for their existence.

P.s. don't mind the bottom bar about Bluetooth eventually appearing, it's just Gadgetbridge complaining.

**Comment by Cynosphere** [comment]
@castdrian

**Comment by castdrian** [comment]
yeah there's a condition that retries if denied, perhaps should be a bit more grateful
