### ISSUE TITLE
Feature request: Custom Icon

### ISSUE THREAD

**Issue by ROBGUI09** [vendetta-mod/VendettaManager#7]
Ability to set any custom png with aspect ratio 1:1 as app icon

**Comment by wingio** [comment]
Just use a 3rd party launcher that supports this

**Comment by VioletStorm** [comment]
> Just use a 3rd party launcher that supports this

This doesn't change anything system wide

**Comment by VioletStorm** [comment]
> So?

That matters to people, having an icon updated system wide improves continuity and clarity

**Comment by wingio** [comment]
For most people the icon will only show up in two places: The launcher and the app switcher. I doubt many people even pay attention to the latter.

As for the main reason for not implementing this, replacing the icon isn't as simple as replacing one image, its 3 separate images all with different levels of cropping.

**Comment by wingio** [comment]
Only premade could work but i don't know if its really necessary for the purposes of this app, I don't really want it to succumb to feature creep

**Comment by VioletStorm** [comment]
> Only premade could work but i don't know if its really necessary for the purposes of this app, I don't really want it to succumb to feature creep


Selectable app images are an increasingly popular feature, with WhatsApp, Signal, Snapchat, Telegram, ect all adding this feature as a premium luxury. Considering this I wouldn't imagine this would crossing the line into feature creep or bloat

It is reasonable to assume discord themselves will add this feature soon, but of course as a nitro only perk. There has been a trend of messaging apps joining in on this feature lately. The point of vendetta is to give users access to customisability and premium features, so I would argue this slots in perfectly with that goal

At the end of this I'll include examples of how some apps implement this. Ultimately though, I think it could be quite a good addition! I would even be happy to make all the icons for you lot just to contribute. I could make basic coloured ones but also some fancy ones similar to how other platforms do things if that ever becomes desired

One final thing, this is more than just cosmetic as with the other apps I've mentioned. For people cloning the app through the manager, this does add the admittedly advanced ability to have icon continuity across ones entire system, which might not seem particularly useful, but there are situations where this comes into play. All in all I hope you at least consider it, and again I'll be happy to do the icon work, I'll provide all necessary sizes and if anyone on your team has any requests I would also make any and all of those!

![Screenshot_20230614-070941_Signal.png](https://github.com/vendetta-mod/VendettaManager/assets/54405427/1e2f59cb-3f6b-4beb-b54d-57dafea32436)

![Screenshot_20230614-070738_Telegram.png](https://github.com/vendetta-mod/VendettaManager/assets/54405427/efcf0b2c-2313-4a18-afd2-03467de0cf89)

![Uploading Screenshot_20230614-070927_Snapchat.png …]()

**Comment by VioletStorm** [comment]
![Screenshot_20230614-072653_Snapchat.png](https://github.com/vendetta-mod/VendettaManager/assets/54405427/620b6574-3667-4146-b8a4-7b3acae18b69)

**Comment by wingio** [comment]
This is a feature i believe should be implemented by discord themselves (its actually easier for them to do it rather than me). I just don't want to fill manager with a ton of features that most people won't even use and have better alternative methods anyways.

**Comment by VioletStorm** [comment]
> This is a feature i believe should be implemented by discord themselves (its actually easier for them to do it rather than me). I just don't want to fill manager with a ton of features that most people won't even use and have better alternative methods anyways.

Only thing is Discord is guaranteed to lock it behind Nitro. What are the existing better alternatives though?

**Comment by wingio** [comment]
If it ends up locked behind nitro then a plugin can unlock it.

And i was referring to using a launcher as the better alternative bc it would offer more freedom than what i can offer.

**Comment by Efreak** [comment]
@wingio I don't care if it's actually configurable or not, but please at least modify the app/notification icon in *some* way (making it cyan is acceptable, as is a V icon or just about anything else) *so that I don't have identical notifications for different apps*. I use a bunch of plugins because I'm weird like that, and when I think one of them is interfering I switch to Discord; this means that certain messages get doubled notifications, and I can't tell which is from Discord and which is from Vendetta.

While I don't use the default icons in my launcher anyways, this will also help users that don't have themeable icons to differentiate; most people aren't going to install a 3rd party launcher just to get themeable icons. If not for my use case above, I'd actually suggest just using a shortcut; there's plenty of apps that will create custom launcher shortcuts for other apps with different icons.

**Comment by VioletStorm** [comment]
> @wingio I don't care if it's actually configurable or not, but please at least modify the app/notification icon in *some* way (making it cyan is acceptable, as is a V icon or just about anything else) *so that I don't have identical notifications for different apps*. I use a bunch of plugins because I'm weird like that, and when I think one of them is interfering I switch to Discord; this means that certain messages get doubled notifications, and I can't tell which is from Discord and which is from Vendetta.
> 
> While I don't use the default icons in my launcher anyways, this will also help users that don't have themeable icons to differentiate; most people aren't going to install a 3rd party launcher just to get themeable icons. If not for my use case above, I'd actually suggest just using a shortcut; there's plenty of apps that will create custom launcher shortcuts for other apps with different icons.

^
