### ISSUE TITLE
Possible Trojan in Vendetta

### ISSUE THREAD

**Issue by CrytosGtag** [vendetta-mod/VendettaManager#72]
I scanned it with Virustotal and it has 4 Detections including google lmk if these are just False Positives
https://www.virustotal.com/gui/file/44ff7434a04ce6939097deeb8dd6f892f93261c082f2ae482db7b50eb9106824

**Comment by Cynosphere** [comment]
false positives

**Comment by aimarket** [comment]
Weird stuff started happening with people knowing too much personal info only on my discord after downloading this app. Which sucks because I wanted this app. Now I'm too scared to try again

**Comment by Cynosphere** [comment]
If you didn't download it from GitHub or installed unproxied plugins from, that's on you.
