### ISSUE TITLE
why is Vendetta discontinued?

### ISSUE THREAD

**Issue by tkbstudios** [vendetta-mod/VendettaManager#74]
Hello I'm here because I just noticed that nothing worked anymore and saw that vendetta got discontinued, by why?

**Comment by Cynosphere** [comment]
![Screenshot of the end of life channel in the Discord](https://github.com/vendetta-mod/VendettaManager/assets/1606710/cac0f8c1-259c-4481-9da1-f884146f679a)

**Comment by tkbstudios** [comment]
Thanks :)

**Comment by tkbstudios** [comment]
It's sad what happenend :(
