### ISSUE TITLE
Display update progress bar and update progress in installer screen 

### ISSUE THREAD

**Issue by soymadip** [vendetta-mod/VendettaManager#8]
It will be visually good and useful if progress bar is added with down[]()![IMG_20230501_222126.jpg](https://user-images.githubusercontent.com/84225810/235491453-ea21b5fa-416a-441c-af13-797f14e30b30.jpg)

load size.

**Comment by wingio** [comment]
manager uses androids download manager, which unfortunately doesn't provide any way for me to add this. However it does send a notification with the progress

**Comment by soymadip** [comment]
Ohh, i get it🙂
