### ISSUE TITLE
Manager crashes when interact

### ISSUE THREAD

**Issue by dearminder** [vendetta-mod/VendettaManager#9]
App crashes after click Install or Settings
Log: https://pastebin.com/i5gPG2KE
Android 13

**Comment by wingio** [comment]
those logs appear to be incomplete, only part of the stacktrace is shown

**Comment by dearminder** [comment]
ok used other app without filters https://pastebin.com/ZGYXEqMg

**Comment by wingio** [comment]
hmm it seems that the external cache directory is null, might be an issue with your rom

**Comment by dearminder** [comment]
I am pretty sure rom is ok. Isn't this issue connected with Environment.getExternalStorageDirectory() being deprecated on API 29?

**Comment by wingio** [comment]
i don't use that anywhere

**Comment by dearminder** [comment]
it is used on https://github.com/vendetta-mod/VendettaManager/blob/main/app/src/main/java/dev/beefers/vendetta/manager/utils/Constants.kt

**Comment by wingio** [comment]
ok yeah but that's not whats causing the issue, its the fact that context.externalCacheDir is returning null

**Comment by wingio** [comment]
forgot to mention that i fixed this issue
